[project]
name = "mollana"
version = "0.1.3"
description = "Urdu roman transliterated text editor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "confz>=2.1.0",
    "pydantic>=2.12.5",
    "pyside6>=6.10.1",
    "strenum>=0.4.15",
    "symspellpy>=6.9.0",
    "tomlkit>=0.13.3",
    "spacy>=3.8.14",
    "unicodedataplus>=16.0.0.post1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.17.0",
    "pytest>=9.0.2",
]
